import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.bold]
# BlexMono, ComicMono, JetBrainsMono, AnonymicePro Nerd Font, Comic Code, MonoLisa
# BlexMono, ComicMono, JetBrainsMono, AnonymicePro, Comic Code Ligatures, MonoLisa
family = "Comic Code Ligatures"
style = "Bold"

[font.bold_italic]
family = "Comic Code Ligatures"
style = "Bold Italic"

[font.italic]
family = "Comic Code Ligatures"
style = "Italic"

[font.normal]
family = "Comic Code Ligatures"
style = "Regular"

[font.offset]
x = 1
y = 3

[window]
decorations = "none"
opacity = 1
option_as_alt = "Both"

[window.padding]
x = 3
y = 3

[window.position]
x = 0
y = 0

# Alacritty Configuration (TOML)
[keyboard]

bindings = [
  # Command+Shift+Letter
  { key = "a", mods = "Command|Shift", chars = "ğŸš€" },
  { key = "b", mods = "Command|Shift", chars = "ğŸŒŸ" },
  { key = "c", mods = "Command|Shift", chars = "ğŸ‰" },
  { key = "d", mods = "Command|Shift", chars = "ğŸˆ" },
  { key = "e", mods = "Command|Shift", chars = "ğŸ" },
  { key = "f", mods = "Command|Shift", chars = "ğŸ„" },
  { key = "g", mods = "Command|Shift", chars = "ğŸƒ" },
  { key = "h", mods = "Command|Shift", chars = "ğŸ†" },
  { key = "i", mods = "Command|Shift", chars = "ğŸ‡" },
  { key = "j", mods = "Command|Shift", chars = "ğŸ¸" },
  { key = "k", mods = "Command|Shift", chars = "ğŸ¤" },
  { key = "l", mods = "Command|Shift", chars = "ğŸµ" },
  { key = "m", mods = "Command|Shift", chars = "ğŸ¶" },
  { key = "n", mods = "Command|Shift", chars = "ğŸ†" },
  { key = "o", mods = "Command|Shift", chars = "ğŸ…" },
  { key = "p", mods = "Command|Shift", chars = "ğŸ¥‡" },
  { key = "q", mods = "Command|Shift", chars = "ğŸ¥ˆ" },
  { key = "r", mods = "Command|Shift", chars = "ğŸ¥‰" },
  { key = "s", mods = "Command|Shift", chars = "ğŸš´" },
  { key = "t", mods = "Command|Shift", chars = "ğŸšµ" },
  { key = "u", mods = "Command|Shift", chars = "ğŸ‹ï¸" },

  # Command+Letter
  { key = "Tab", mods = "Control", chars = "ğŸ‘" },
  { key = "a", mods = "Command", chars = "ğŸ˜€" },
  { key = "b", mods = "Command", chars = "ğŸ˜" },
  { key = "c", mods = "Command", chars = "ğŸ˜‚" },
  { key = "d", mods = "Command", chars = "ğŸ¤£" },
  { key = "e", mods = "Command", chars = "ğŸ˜ƒ" },
  { key = "f", mods = "Command", chars = "ğŸ˜„" },
  { key = "g", mods = "Command", chars = "ğŸ˜…" },
  { key = "h", mods = "Command", chars = "ğŸ˜†" },
  { key = "i", mods = "Command", chars = "ğŸ˜‰" },
  { key = "j", mods = "Command", chars = "ğŸ˜Š" },
  { key = "k", mods = "Command", chars = "ğŸ˜‹" },
  { key = "l", mods = "Command", chars = "ğŸ˜" },
  { key = "m", mods = "Command", chars = "ğŸ˜" },
  { key = "n", mods = "Command", chars = "ğŸ˜˜" },
  { key = "o", mods = "Command", chars = "ğŸ˜—" },
  { key = "p", mods = "Command", chars = "ğŸ˜™" },
  { key = "q", mods = "Command", chars = "ğŸ˜š" },
  { key = "r", mods = "Command", chars = "ğŸ™‚" },
  { key = "s", mods = "Command", chars = "ğŸ¤—" },
  { key = "t", mods = "Command", chars = "ğŸ¤©" },
  { key = "u", mods = "Command", chars = "ğŸ¤”" },
  # { key = "v", mods = "Command", chars = "ğŸ¤¨" },
  { key = "w", mods = "Command", chars = "ğŸ˜" },
  { key = "x", mods = "Command", chars = "ğŸ˜‘" },
  { key = "y", mods = "Command", chars = "ğŸ˜¶" },
  { key = "z", mods = "Command", chars = "ğŸ™„" },

  # Numbers
  { key = "1", mods = "Command", chars = "ğŸŒŸ" },
  { key = "2", mods = "Command", chars = "ğŸ”¥" },
  { key = "3", mods = "Command", chars = "ğŸŒˆ" },
  { key = "4", mods = "Command", chars = "ğŸ€" },
  { key = "5", mods = "Command", chars = "ğŸŒ¹" },
  { key = "6", mods = "Command", chars = "ğŸµ" },
  { key = "7", mods = "Command", chars = "âš¡" },
  { key = "8", mods = "Command", chars = "ğŸŒ" },
  { key = "9", mods = "Command", chars = "ğŸŒ™" },
  { key = "0", mods = "Command", chars = "â­" },


  # Non-letter, non-number keys with non-face emojis
  { key = "Space", mods = "Command", chars = "ğŸ””" },
  { key = "Tab", mods = "Command", chars = "ğŸ”‘" },
  { key = "Enter", mods = "Command", chars = "ğŸ“¥" },
  { key = "Backspace", mods = "Command", chars = "ğŸ—‘ï¸" },
  { key = "-", mods = "Command", chars = "â–" },
  { key = "|", mods = "Command", chars = "â•" },
  { key = "[", mods = "Command", chars = "ğŸ“š" },
  { key = "]", mods = "Command", chars = "ğŸ“–" },
  { key = "\\", mods = "Command", chars = "ğŸ”™" },
  { key = ";", mods = "Command", chars = "ğŸ“" },
  { key = "'", mods = "Command", chars = "âœ’ï¸" },
  { key = ",", mods = "Command", chars = "ğŸ—’ï¸" },
  { key = ".", mods = "Command", chars = "ğŸ“Œ" },
  { key = "/", mods = "Command", chars = "ğŸ—‚ï¸" },
  { key = "`", mods = "Command", chars = "ğŸ’¡" },
  { key = "Up", mods = "Command", chars = "â¬†ï¸" },
  { key = "Down", mods = "Command", chars = "â¬‡ï¸" },
  { key = "Left", mods = "Command", chars = "â¬…ï¸" },
  { key = "Right", mods = "Command", chars = "â¡ï¸" },
]
